export const consDict = [
    {sound:"p", file:"p", example: "Peter picked a peck of pickled peppers.", letters:"p, P"}, 
    {sound:"b", file:"b", example: "The baby played with a blue ball.", letters:"b, B"}, 
    {sound:"k", file:"k", example: "Kevin kicked the ball over the fence.", letters:"k, K"}, 
    {sound:"g", file:"g", example: "Greg gave Gary a gift for his birthday.", letters:"g, G"}, 
    {sound:"f", file:"f", example: "Frank fried fish for dinner.", letters:"f, F"}, 
    {sound:"v", file:"v", example: "Victor visited the vast vineyard.", letters:"v, V"}, 
    {sound:"t", file:"t", example: "Tom takes the trash out every morning.", letters:"t, T"}, 
    {sound:"d", file:"d", example: "The dog dug a deep hole in the yard.", letters:"d, D"},
    {sound:"s", file:"s", example: "Sally sings the song so well.", letters:"s, S"},  
    {sound:"z", file:"z", example: "The zoo had a new zookeeper this year.", letters:"z, Z"}, 
    {sound:"ʃ", file:"ʃ", example: "She sells sea shells on a shore.", letters:"h"}, 
    {sound:"ʒ", file:"ʒ", example: "She wore a beige dress.", letters:"g"}, 
    {sound:"θ", file:"θ", example: "Three people think quick.", letters:"th, Th"}, 
    {sound:"ð", file:"ð", example: "The weather is very warm.", letters:"th, Th"},
    {sound:"tʃ", file:"tʃ", example:"Chester Cheetah chooses a chunk of cheap cheddar cheese.", letters:"ch, Ch"}, 
    {sound:"dʒ", file:"dʒ", example: "Jane jumped joyfully on the trampoline.", letters:"j, J"}, 
    {sound:"l", file:"l", example: "Larry loves to laugh.", letters:"l, L"}, 
    {sound:"r", file:"r", example: "Robert ran a race around the river park.", letters:"r, R"}, 
    {sound:"w", file:"w", example: "William worked hard to win the award.", letters:"w, W"}, 
    {sound:"j", file:"j", example: "The young yogi practiced yoga all morning.", letters:"y, Y"}, 
    {sound:"m", file:"m", example: "Mary made magnificent music with her mandolin.", letters:"m, M"}, 
    {sound:"n", file:"n", example: "Nancy noticed the new necklace in the window.", letters:"n, N"}, 
    {sound:"ŋ", file:"ŋ", example: "The king's song was long.", letters:"ng"}, 
    {sound:"h", file:"h", example: "Harry is a hairdresser.", letters:"h, H"},  
];